FROM bethgelab/deeplearning:future

RUN pip install torch
RUN pip install torchvision
RUN pip install tensorboardX
RUN pip install scikit-image
RUN pip install SQLAlchemy
RUN pip install GitPython
RUN pip install torchsummary
